### ISSUE TITLE
Support for Windows (10/11)

### ISSUE THREAD

**Issue by FlexcalAdmin** [josephcrowell/flutter_record#2]
**What version of this package are you using?**
Latest
**What problem do you want to solve?**
It does not support Windows platform
**What do you think is the correct solution to this problem?**
Support Windows 10 or 11
**Are you willing to submit a pull request to implement this change?**
No

**Comment by josephcrowell** [comment]
https://github.com/llfbandit/record supports Windows platforms. There are no plans to extend this package beyond Android and iOS.
