### ISSUE TITLE
Chunks array is empty

### ISSUE THREAD

**Issue by BennyKirschner** [josephcrowell/flutter_record#3]
In line 114, it's supposed to say 'dataavaiable'. The package currently listens to the event 'dataAvailable' which causes the bug.

![image](https://github.com/josephcrowell/flutter_sound_record/assets/15686206/3afb88df-cdc5-4103-b508-c25d28119e36)

**Comment by josephcrowell** [comment]
Could you fork and make that change and do a pull request? That way you get credit for the fix in the commit history.
